// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUYGGRjus1zzxne2jqsDomcxuF8F5oVEw',
    appId: '1:212453985976:web:de033ed9ddc134c3766e4d',
    messagingSenderId: '212453985976',
    projectId: 'smart-travel-list',
    authDomain: 'smart-travel-list.firebaseapp.com',
    storageBucket: 'smart-travel-list.firebasestorage.app',
    measurementId: 'G-1GGWBQ5QL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD65rSxfQ5VkSvG5X1tZFQ5EZ22HAFo4XU',
    appId: '1:212453985976:android:e6e150f787f8c438766e4d',
    messagingSenderId: '212453985976',
    projectId: 'smart-travel-list',
    storageBucket: 'smart-travel-list.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvyWT8pBEf1e9wD5ygeAypQsnGZSuyvgw',
    appId: '1:212453985976:ios:ae87653b1c4466a2766e4d',
    messagingSenderId: '212453985976',
    projectId: 'smart-travel-list',
    storageBucket: 'smart-travel-list.firebasestorage.app',
    iosBundleId: 'com.smarttravellist.app',
  );

}